#!/bin/sh
exec tail -n +3 $0
menuentry "Remix OS" {
        load_video
        insmod gzio
        gfxmode $linux_gfx_mode
        insmod part_gpt
        insmod ext2
        set root='hd0,gpt13'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt13 --hint-efi=hd0,gpt13 --hint-baremetal=achi0,gpt13 033e8fc7-4cfe-9454-bc59-df7329ca862d
        else
          search --no-floppy --fs-uuid --set=root 033e8fc7-4cfe-9454-bc59-df7329ca862d
        fi
        echo 'Loading Kernel...'
        linux /RemixOS/kernel quiet root=/dev/ram0 androidboot.hardware=remix_x86_64 androidboot.selinux=permissive SRC=/RemixOS SERIAL=random logo.showlogo=1 DATA= DEBUG=
        echo 'Loading Initial Ramdisk...'
        initrd /RemixOS/initrd.img
} 
